openapi: 3.2.0
info:
  title: Stellar Disbursement Platform Exports API
  version: 2.1.0
  summary: The Stellar Disbursement Platform (SDP) is a tool built for organizations to make bulk payments to a group of recipients over the Stellar network.
  description: 'The Stellar Disbursement Platform (SDP) is a tool built for organizations to make bulk payments to a group of recipients over the Stellar network.


    This is an open-source project that is built on top of the Stellar network, and the code can be found on the following repositories:


    - [stellar/stellar-disbursement-platform-backend](https://github.com/stellar/stellar-disbursement-platform-backend): This repository contains the backend and infrastructure code for the Stellar Disbursement Platform.

    - [stellar/stellar-disbursement-platform-frontend](https://github.com/stellar/stellar-disbursement-platform-frontend): This repository contains the web frontend code for the Stellar Disbursement Platform.

    - [stellar/helm-charts](https://github.com/stellar/helm-charts/tree/main/charts/stellar-disbursement-platform): This repository contains the Helm chart for deploying the Stellar Disbursement Platform using kubernetes.

    '
  termsOfService: https://stellar.org/terms-of-service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: ''
tags:
- name: Exports
paths:
  /exports/disbursements:
    get:
      tags:
      - Exports
      summary: Export Disbursements
      description: Exports a CSV file of disbursements.
      operationId: exportDisbursements
      parameters:
      - name: q
        in: query
        description: A search term used to query through the disbursement names.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: status
        in: query
        description: Comma-separated list of disbursement statuses to filter by.
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/DisbursementStatus'
        example: DRAFT
      - name: created_at_after
        in: query
        description: 'Only return disbursements that are created after this date. Format: YYYY-MM-DD'
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: '2006-01-02'
      - name: created_at_before
        in: query
        description: 'Only return disbursements that are created before this date. Format: YYYY-MM-DD'
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: '2006-01-02'
      - name: sort
        in: query
        description: Field used to sort disbursements
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: created_at
          enum:
          - name
          - created_at
      - name: direction
        in: query
        description: Direction for sorting disbursements.
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: desc
          enum:
          - asc
          - desc
      responses:
        '200':
          description: CSV file of disbursements
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          description: Forbidden
          $ref: '#/components/responses/ForbiddenResponse'
      security:
      - BearerAuth: []
  /exports/payments:
    get:
      tags:
      - Exports
      summary: Export Payments
      description: Exports a CSV file of payments.
      operationId: exportPaymentsCSV
      parameters:
      - name: q
        in: query
        description: Search payments by ID, external_payment_id, receiver wallet address, or disbursement name.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: type
        in: query
        description: Type of payments
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - DIRECT
          - DISBURSEMENT
      - name: status
        in: query
        description: Exact match on the status of the payment.
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/PaymentStatus'
        example: DRAFT
      - name: receiver_id
        in: query
        description: UUID that represents a receiver in the database
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: b6b667ad-6cc2-46cf-9be7-561daace7d48
      - name: created_at_after
        in: query
        description: 'Only return payments that are created after this date. Format: YYYY-MM-DD'
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: '2006-01-02'
      - name: created_at_before
        in: query
        description: 'Only return payments that are created before this date. Format: YYYY-MM-DD'
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: '2006-01-02'
      - name: sort
        in: query
        description: Field used to sort payments.
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: updated_at
          enum:
          - updated_at
          - created_at
      - name: direction
        in: query
        description: Direction for sorting payments.
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: desc
          enum:
          - asc
          - desc
      responses:
        '200':
          description: CSV file of payments
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          description: Forbidden
          $ref: '#/components/responses/ForbiddenResponse'
      security:
      - BearerAuth: []
  /exports/receivers:
    get:
      tags:
      - Exports
      summary: Export Receivers
      description: Exports a CSV file of receivers.
      operationId: exportReceiversCSV
      parameters:
      - name: q
        in: query
        description: A search term used to query through the receiver phone_number, email, and ID.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: status
        in: query
        description: Exact match on the status of the receiver wallet.
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/ReceiversWalletStatus'
        example: DRAFT
      - name: created_at_after
        in: query
        description: 'Only return receivers that are created after this date. Format: YYYY-MM-DD'
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: '2006-01-02'
      - name: created_at_before
        in: query
        description: 'Only return receivers that are created before this date. Format: YYYY-MM-DD'
        required: false
        style: form
        explode: true
        schema:
          type: string
        example: '2006-01-02'
      - name: sort
        in: query
        description: Field used to sort receivers
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: updated_at
          enum:
          - updated_at
          - created_at
      - name: direction
        in: query
        description: Direction for sorting receivers.
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: desc
          enum:
          - asc
          - desc
      responses:
        '200':
          description: CSV file of receivers
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          description: Forbidden
          $ref: '#/components/responses/ForbiddenResponse'
      security:
      - BearerAuth: []
components:
  schemas:
    PaymentStatus:
      type: string
      description: The status of the payment
      enum:
      - DRAFT
      - READY
      - PENDING
      - PAUSED
      - SUCCESS
      - FAILED
      - CANCELED
    ReceiversWalletStatus:
      type: string
      enum:
      - DRAFT
      - READY
      - REGISTERED
      - FLAGGED
    DisbursementStatus:
      type: string
      enum:
      - DRAFT
      - READY
      - STARTED
      - PAUSED
      - COMPLETED
  responses:
    UnauthorizedResponse:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              extras:
                type: object
                properties:
                  status:
                    type: number
                  message:
                    type: string
          example:
            error: Not authorized
            extras:
              status: 401
              message: Not authorized
    ForbiddenResponse:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
          example:
            error: Forbidden
  securitySchemes:
    BearerAuth:
      type: apiKey
      description: Authorization header containing an SDP JWT (ES256) or an SDP_ API key.
      name: Authorization
      in: header
    SEP10Auth:
      type: apiKey
      description: Authorization header containing a SEP-10 JWT (Bearer {token}).
      name: Authorization
      in: header
    SEP24Auth:
      type: apiKey
      description: Authorization header containing a SEP-24 JWT (Bearer {token}).
      name: Authorization
      in: header
    SEP24QueryAuth:
      type: apiKey
      description: Query parameter containing a SEP-24 JWT.
      name: token
      in: query
x-original-swagger-version: '2.0'
